version: "3"
services:
  golang:
    image: registry.cn-shenzhen.aliyuncs.com/xyg/golang:latest
    ports:
      - 8088:8088
    links:
      - "mysql"
      - "redis"
    volumes:
      - ./go:/go
    tty: true     
  mysql:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    volumes:
      - ./golang-mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: redis:4.0.10-alpine
    ports:
      - 6379:6379